---
title: "R 05.08.2024"
output: html_notebook
---

#Vetores
#Exercício fáicl: Crie um vetor com os numeros de 1 a  10 e imprima

vetor<- 1:10
print(vetor)

#Exercício fácil: Crie um vetor com números pares de 2 a 20 e imprima
vetor <- seq(2,20,by=2)
print(vetor)

#Exercício médio: Calcule a soma dos elementos de um vetor com números de 1 a 100
vetor<-1:100
soma<- sum(vetor)
print(soma)

#Exercíco médio: Encontre o maior e o menor valor em um vetor de números aleatórios entre 1 e 1000, de tamanho 50
vetor<-sample(1:1000, 50, replace = TRUE)
maior<-max(vetor)
menor<-min(vetor)
print(paste("Maior:", maior, "Menor:",menor))

#Exemplo de replace
x= sample(1:10,3, replace=TRUE)
print(x)


#Exercício Díficil, crie um vetor com os 10 primeiros números primos
eh_primo <- function(n){
  if(n<= 1){
    return(FALSE)
  }
  for (i in 2:sqrt(n)) {
    if (n %% i == 0){
      return (FALSE)
    }
  }
  return(TRUE)
}

primos <- c()
num <- 2
while (length(primos)<10){
  if(eh_primo(num)){
    primos <- c(primos, num)
  }
  num <- num + 1
}

print(primos)

#Exercicio Dificil: Inverta a ordem dos elementos de um vetor de tamanho 20, preenchido com numeros aleatorios

vetor <- sample(1:100, 20, replace = TRUE)
vetor_invertido <- rev(vetor)
print(vetor)
print(vetor_invertido)

#Matrizes em Python
#Exercício Fácil: crie uma matriz 3x3 com os números de 1 a 9
matriz <- matrix(1:9, nrow =3, ncol =3)
print(matriz)

#Exercicio Fácil: crie uma matriz identidade 4x4
matriz <- diag(4)
print(matriz)

#Exercicio Medio: some duas matrizes 2x2
matriz1 <- matrix(c(1,2,3,4), nrow = 2, ncol =2)
matriz2 <- matrix(c(5,6,7,8), nrow = 2, ncol =2)
soma_matriz <- matriz1 + matriz2
print(matriz1)
print(matriz2)
print(soma_matriz)

#Exercicio Medio: multiplique duas matrizes 2x2
matriz1 <- matrix(c(1,2,3,4), nrow = 2, ncol =2)
matriz2 <- matrix(c(5,6,7,8), nrow = 2, ncol =2)
prod_matriz <- matriz1 %*% matriz2
print(matriz1)
print(matriz2)
print(prod_matriz)


#Exercicio Dificil: calcule a transposta de uma matriz 3x3
matriz <- matrix(c(1,2,3,4,5,6,7,8,9), nrow =3, ncol =3)
matriz_transposta <- t(matriz)
print(matriz)
print(matriz_transposta)

#Exercicio Dificil: calcule a determinante de uma matriz 3x3
matriz <- matrix(1:9, nrow = 3, ncol = 3)
determinante <- det(matriz)
print(determinante)